import { appendFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { CandidateCatalog } from "../discovery/types.ts";
import { classifyCandidate, TAXONOMY } from "./taxonomy.ts";
import {
  REVIEW_ACTIONS,
  type CandidateReview,
  type ReviewAction,
  type ReviewEvent,
  type ReviewState,
} from "./types.ts";

export async function loadReviewState(
  catalogPath: string,
  eventsPath: string,
): Promise<ReviewState> {
  const catalog = JSON.parse(await readFile(catalogPath, "utf8")) as CandidateCatalog;
  const events = await loadEvents(eventsPath);
  const latestByCandidate = new Map<string, ReviewEvent>();
  for (const event of events) latestByCandidate.set(event.candidateId, event);

  const candidates = catalog.candidates.map((candidate) => {
    const review = projectReview(latestByCandidate.get(candidate.id));
    const dedicatedTest = candidate.artifact.testPaths.some((path) => {
      const stem = candidate.name.replace(/^.*\//, "");
      return path.includes(stem);
    });
    return {
      ...candidate,
      taxonomy: classifyCandidate(candidate),
      review,
      evidence: {
        testCoverage:
          candidate.artifact.testPaths.length === 0
            ? ("none" as const)
            : dedicatedTest
              ? ("dedicated" as const)
              : ("linked" as const),
        failedConditionCount: candidate.admission.failedConditions.length,
      },
    };
  });

  const domains = TAXONOMY.map(({ domain, categories }) => ({
    domain,
    count: candidates.filter((candidate) => candidate.taxonomy.domain === domain).length,
    categories: categories.map((category) => ({
      category,
      count: candidates.filter(
        (candidate) =>
          candidate.taxonomy.domain === domain && candidate.taxonomy.category === category,
      ).length,
    })),
  }));

  return {
    generatedAt: new Date().toISOString(),
    catalogGeneratedAt: catalog.generatedAt,
    candidates,
    domains,
    counts: {
      total: candidates.length,
      unreviewed: candidates.filter(({ review }) => review.status === "unreviewed").length,
      kept: candidates.filter(({ review }) => review.status === "kept").length,
      decided: candidates.filter(({ review }) => review.status === "decided").length,
    },
  };
}

export async function recordReviewEvent(
  catalogPath: string,
  eventsPath: string,
  input: {
    candidateId: string;
    action: string;
    rationale?: string;
    mergeTargetId?: string;
  },
): Promise<ReviewEvent> {
  if (!REVIEW_ACTIONS.includes(input.action as ReviewAction)) {
    throw new Error(`Invalid review action: ${input.action}`);
  }
  const catalog = JSON.parse(await readFile(catalogPath, "utf8")) as CandidateCatalog;
  const candidate = catalog.candidates.find(({ id }) => id === input.candidateId);
  if (!candidate) throw new Error(`Unknown candidate: ${input.candidateId}`);
  if (input.action === "merge" && !input.mergeTargetId) {
    throw new Error("Merge requires a target candidate ID");
  }

  const event: ReviewEvent = {
    eventId: crypto.randomUUID(),
    candidateId: candidate.id,
    candidateRevision: candidate.fingerprint,
    action: input.action as ReviewAction,
    rationale: input.rationale?.trim() ?? "",
    createdAt: new Date().toISOString(),
    ...(input.mergeTargetId ? { mergeTargetId: input.mergeTargetId } : {}),
  };
  await mkdir(dirname(eventsPath), { recursive: true });
  await appendFile(eventsPath, `${JSON.stringify(event)}\n`);
  return event;
}

export async function generateReviewOutputs(
  state: ReviewState,
  statePath: string,
  summaryPath: string,
): Promise<void> {
  await Promise.all([
    mkdir(dirname(statePath), { recursive: true }),
    mkdir(dirname(summaryPath), { recursive: true }),
  ]);
  await Promise.all([
    writeFile(statePath, `${JSON.stringify(state, null, 2)}\n`),
    writeFile(summaryPath, renderReviewSummary(state)),
  ]);
  await formatFiles([statePath, summaryPath]);
}

async function formatFiles(paths: string[]): Promise<void> {
  const formatter = join(import.meta.dir, "../../node_modules/.bin/oxfmt");
  const process = Bun.spawn([formatter, ...paths], { stdout: "pipe", stderr: "pipe" });
  const [stderr, exitCode] = await Promise.all([
    new Response(process.stderr).text(),
    process.exited,
  ]);
  if (exitCode !== 0) throw new Error(`Failed to format review outputs: ${stderr.trim()}`);
}

export function renderReviewSummary(state: ReviewState): string {
  const sections = [
    ["Kept for evaluation", state.candidates.filter(({ review }) => review.status === "kept")],
    ["Decided", state.candidates.filter(({ review }) => review.status === "decided")],
  ] as const;
  return `<!-- Generated by the local review app. Do not edit. -->

# Rule review summary

- Total: ${state.counts.total}
- Unreviewed: ${state.counts.unreviewed}
- Kept: ${state.counts.kept}
- Decided: ${state.counts.decided}

${sections
  .map(
    ([heading, candidates]) => `## ${heading}

${
  candidates.length === 0
    ? "_None._"
    : `| Rule | Semantic home | Decision | Rationale |\n| --- | --- | --- | --- |\n${candidates
        .map(
          (candidate) =>
            `| \`${candidate.name}\` | ${candidate.taxonomy.domain} / ${candidate.taxonomy.category} | ${candidate.review.action ?? "—"} | ${escapeCell(candidate.review.rationale ?? "")} |`,
        )
        .join("\n")}`
}`,
  )
  .join("\n\n")}
`;
}

async function loadEvents(path: string): Promise<ReviewEvent[]> {
  let content: string;
  try {
    content = await readFile(path, "utf8");
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") return [];
    throw error;
  }
  return content
    .split("\n")
    .filter((line) => line.trim().length > 0)
    .map((line) => JSON.parse(line) as ReviewEvent);
}

function projectReview(event: ReviewEvent | undefined): CandidateReview {
  if (!event || event.action === "reopen") return { status: "unreviewed" };
  if (event.action === "keep") {
    return {
      status: "kept",
      action: event.action,
      rationale: event.rationale,
      updatedAt: event.createdAt,
    };
  }
  return {
    status: "decided",
    action: event.action,
    rationale: event.rationale,
    updatedAt: event.createdAt,
    ...(event.mergeTargetId ? { mergeTargetId: event.mergeTargetId } : {}),
  };
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replace(/\s+/g, " ").trim();
}
