import type { CandidateCatalog, Classification, RuleCandidate } from "./types.ts";

const CLASSIFICATION_ORDER: Classification[] = [
  "correctness-candidate",
  "preference-candidate",
  "native-duplicate",
  "project-specific",
  "native-policy",
  "rejected",
  "unreviewed",
];

const CLASSIFICATION_HEADING: { [K in Classification]: string } = {
  "correctness-candidate": "Correctness candidates",
  "preference-candidate": "Preference candidates",
  "native-duplicate": "Native Oxlint duplicates",
  "project-specific": "Project- or stack-specific",
  "native-policy": "Configured Oxlint policy",
  rejected: "Rejected",
  unreviewed: "Unreviewed",
};

export function renderCatalog(catalog: CandidateCatalog): string {
  const counts = new Map<Classification, number>();
  for (const candidate of catalog.candidates) {
    counts.set(
      candidate.admission.classification,
      (counts.get(candidate.admission.classification) ?? 0) + 1,
    );
  }

  const sections = CLASSIFICATION_ORDER.flatMap((classification) => {
    const candidates = catalog.candidates.filter(
      (candidate) => candidate.admission.classification === classification,
    );
    return candidates.length === 0 ? [] : [renderSection(classification, candidates)];
  });

  return `<!-- Generated by bun run discovery:report. Do not edit. -->

# Discovery candidate catalog

Generated from pinned repository commits. A candidate is not an admitted anti-slop rule. Promotion still requires every condition in [the admission standard](../admission-standard.md).

- Generated: ${catalog.generatedAt}
- Sources: ${catalog.sources.length}
- Candidates: ${catalog.candidates.length}
${CLASSIFICATION_ORDER.map((classification) => `- ${CLASSIFICATION_HEADING[classification]}: ${counts.get(classification) ?? 0}`).join("\n")}

## Sources

| Repository | Ref | Commit |
| --- | --- | --- |
${catalog.sources.map((source) => `| [${source.repository}](https://github.com/${source.repository}/tree/${source.commit}) | \`${source.ref}\` | \`${source.commit.slice(0, 12)}\` |`).join("\n")}

${sections.join("\n\n")}
`;
}

function renderSection(classification: Classification, candidates: RuleCandidate[]): string {
  return `## ${CLASSIFICATION_HEADING[classification]}

| Candidate | Kind | Source | Tests | Description |
| --- | --- | --- | ---: | --- |
${candidates.map(renderRow).join("\n")}`;
}

function renderRow(candidate: RuleCandidate): string {
  const path = candidate.artifact.implementationPaths[0];
  const sourceUrl = `https://github.com/${candidate.source.repository}/blob/${candidate.source.commit}/${path}`;
  const duplicateNote =
    candidate.similarity.exactDuplicates.length + candidate.similarity.relatedCandidates.length > 0
      ? ` Related: ${candidate.similarity.exactDuplicates.length + candidate.similarity.relatedCandidates.length}.`
      : "";
  const missing =
    candidate.admission.failedConditions.length > 0
      ? ` Missing: ${candidate.admission.failedConditions.map(escapeCell).join("; ")}.`
      : "";
  return `| \`${escapeCell(candidate.name)}\` | ${candidate.artifact.kind} | [${candidate.source.repository}](${sourceUrl}) | ${candidate.artifact.testPaths.length} | ${escapeCell(candidate.description)}${duplicateNote}${missing} |`;
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replace(/\s+/g, " ").trim();
}
